### ISSUE TITLE
Question regarding old framework version run

### ISSUE THREAD

**Issue by franchuterivera** [openml/automlbenchmark#163]
Hello, 

I wanted to get some clarification on https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#add-an-automl-framework  --  particularly in the best way of running older tool versions.

Following the guide I tried:

```
 autosklearn_oldgen:
   extends: autosklearn
   version: "0.7.1"
   description: "this will use the latest autosklearn version from the old generation"
```

When I branch a clean repo clone and then launch:

```
python runbenchmark.py autosklearn_oldgen -m local
```

It looks like the version installed is 0.8.0:

```
Running cmd `/home/chico/work/automlbenchmark_fork/frameworks/autosklearn/setup.sh /home/chico/work/automlbenchmark_fork 0.8.0`
```
Also, if you try to use the setup_cmd option, it is tricky with the pip version as I want to use the virtual env for the tool, but I get access only to the system version.

Is there any recommended way to run an old framework?
