### ISSUE TITLE
Accept `failures.csv` to be able to rerun all failed runs in parallel

### ISSUE THREAD

**Issue by sebhrusen** [openml/automlbenchmark#267]

**Comment by PGijsbers** [comment]
How automatic do we do this? Do we want support for multiple frameworks (#169)? What information do we need? Do we only work with `(framework, task, fold, constraint(?))` data, and require the users to provide the additional instructions again (e.g. `mode`)?

**Comment by sebhrusen** [comment]
@PGijsbers `failures.csv` is currently only generated in `aws` mode: I think it should be our primary target mode for this functionality for now.
Here are the columns available in `failures.csv`:
```columns=['framework', 'benchmark', 'constraint', 'task', 'fold', 'seed', 'error'],```
this should be enough to only require the `mode` from the user at first.

One of the main difficulty, I agree, is that it overlaps with #169 , or we could see it this way: `failures.csv` could just be a simpler version of some execution plan:
> python runbenchmark.py execution_plan.csv -m aws
or
> python runbenchmark.py execution_plan.yaml

with `execution_plan.csv`
framework | benchmark | constraint | task | fold | seed
--- | --- | --- | --- | --- | ---
autosklearn | small | 1h8c | | |
autogluon | small | 1h8c | | |
autoxgboost | small | 4h8c | foo, bar, baz | 0, 1, 2 | 0

and/or `execution_plan.yaml`
```yaml
mode: aws
plan:
  - "autosklearn small 1h8c"
  - "autogluon small 1h8c"
  - "autoxgboost small 4h8c -t foo bar baz -f 0 1 2 -Xseed=0"
  - framework: autoxgboost
     benchmark: small
     constraint: 4h8c
     tasks:
       - foo
       - bar
       - baz
     folds: [0, 1, 2]
     seed: 0 
```

I didn't think this through yet, open to suggestions.

However, I think the declarative approach is the right one: as all the information is in one place, and we can more easily imagine a future possibility to abort/resume it.
Also converting the `csv` format to the richer `yaml` format is just trivial, so as soon as we support the latter, we get the first mainly useful to reinject `failures.csv`.

Also, one of the difficulty for this feature is to verify that `failures.csv` contains what we expect :
- does `failures.csv` contains **ALL** the errors that are not due to the framework training itself.
- does `failures.csv` contains **ONLY** the errors that are not due to the framework training itself.
- problem with hanging instances, even when they are interrupted correctly by the hard timeout: are we always sure that it was a framework issue?

Because of all those uncertainties, we may need to filter/edit the failures.csv manually before reinjecting it sometimes, that's why the declarative execution plan looks like the most interesting approach due to its flexibility for all kind of scenarios.
