### ISSUE TITLE
Encoding error causing ResultError

### ISSUE THREAD

**Issue by Robinnibor** [openml/automlbenchmark#466]
I am getting the following error:
```
     id    task fold framework constraint      metric  duration      seed                                                    info
disease disease    0      TPOT       1h4c neg_logloss      68.5 970204891 ResultError: y contains previously unseen labels: '1.0'
```
At first glance I thought that I have label in test data which is unseen in my train data.
However, I still get this error when using the same data for both training and testing

My .yaml looks like this
```
- name: disease
  dataset:
    train: ./test_data/automl_disease.csv
    test:  ./test_data/automl_disease.csv
    target: output
    type: multiclass
    #type: binary
  folds: 1
```

And I find that if I modify the label_encoder in `amlb/data.py` to use int instead of float, the error is gone.
ex:
```
    @lazy_property
    def label_encoder(self):
        return Encoder('label' if self.values is not None else 'no-op',
                       target=self.is_target,
                       encoded_type=int if self.is_target and not self.is_numerical() else int, # <= this "int" was originally "float"
                       missing_values=[None, np.nan, pd.NA],
                       missing_policy='mask' if self.has_missing_values else 'ignore',
                       normalize_fn=self.normalize
                       ).fit(self.values)
```
I am wondering what is the proper way to resolve it.
