### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by sedol1339** [openml/automlbenchmark#593]
Hello! I'm running the following command from unmodified AMLB bencmark repo:

```
python automlbenchmark/runbenchmark.py catboost amlb_full 1h_1fold \
    --indir /data/osedukhin/shared/openml_cache \
    --outdir /data/osedukhin/shared/amlb_results \
    --userdir /data/osedukhin/shared/amlb_configs \
    --exit-on-error
```

User dir contains the following config:

```
frameworks:
  definition_file:
    - '{root}/resources/frameworks.yaml'
    - '{root}/examples/custom/frameworks.yaml'
    - '{user}/frameworks.yaml'
benchmarks:
  definition_dir:
    - '{root}/resources/benchmarks'
    - '{user}/benchmarks'
  constraints_file:
    - '{root}/resources/constraints.yaml'
    - '{user}/constraints.yaml'
```

`{user}/frameworks.yaml` contains the following:

```
CatBoost:
  module: extensions.CatBoost
```

Directory `{user}/frameworks/extensions/CatBoost` contains the following `__init__.py`:

```
def version():
    from catboost import __version__
    return __version__

from amlb.utils import call_script_in_same_dir

print('CatBoost __init.py__')

def setup(*args, **kwargs):
    print('Installing CatBoost')
    call_script_in_same_dir(__file__, "setup.sh", *args, **kwargs)
    
def run(*args, **kwargs):
    from .exec import run
    return run(*args, **kwargs)
```

Also `{user}/frameworks/extensions/CatBoost` contains the following setup.sh:

```
#!/usr/bin/env bash
shopt -s expand_aliases
HERE=$(dirname "$0")

. "$HERE/.setup_env"
. "$AMLB_ROOT/frameworks/shared/setup.sh" "$HERE" true
PIP install -r "$HERE/requirements.txt"

PY -c "from catboost import __version__; print(__version__)" >> "${HERE}/.installed"
```

When i'm starting runbenchmark.py using the above command, I got the following output:

```
Running benchmark `catboost` on `amlb_full` framework in `local` mode.
Loading frameworks definitions from ['/data/osedukhin/shared/automlbenchmark/resources/frameworks.yaml', '/data/osedukhin/shared/automlbenchmark/examples/custom/frameworks.yaml', '/data/osedukhin/shared/amlb_configs/frameworks.yaml'].
Loading benchmark constraint definitions from ['/data/osedukhin/shared/automlbenchmark/resources/constraints.yaml', '/data/osedukhin/shared/amlb_configs/constraints.yaml'].
Loading benchmark definitions from /data/osedukhin/shared/amlb_configs/benchmarks/amlb_full.yaml.
CatBoost __init.py__
fatal: not a git repository (or any parent up to mount point /data/osedukhin)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

[MONITORING] [python [1098707]] CPU Utilization: 2.9%

------------------------------------------------------------
Starting job local.amlb_full.1h_1fold.eucalyptus.0.CatBoost.
............
```

After this, it fails with the error `No module named 'catboost'`.

So, I guess the problem is that __init.py__ is being  run, but setup method in __init.py__ is not being run. What may be the problem?
