### ISSUE TITLE
Support for non-openML datasets

### ISSUE THREAD

**Issue by Tom-Deng** [openml/automlbenchmark#66]
now, raw dataset are not supported. Are there any plans to support it?

**Comment by PGijsbers** [comment]
Could you elaborate what you mean with a raw dataset? Is it still in any particular file format? Can it contain multiple files? Etc.

**Comment by Tom-Deng** [comment]
> Could you elaborate what you mean with a raw dataset? Is it still in any particular file format? Can it contain multiple files? Etc.

In my use case，a raw dataset refers to a local dataset with different formats，such as csv，libsvm，etc.

**Comment by seb-h2o** [comment]
We could easily support local `arff` files as they also contain feature descriptions. We could just agree on using the last attribute as the target (or the one named `target` or `class` as it's also a common convention).
For `csv` files, it would just be slightly more complicated as we would also need to agree on an additional file format to describe the features. But once agreed, it would be relatively easy to integrate.

Not sure that `libsvm` is popular enough as a format to consider it currently.

**Comment by Tom-Deng** [comment]
> We could easily support local `arff` files as they also contain feature descriptions. We could just agree on using the last attribute as the target (or the one named `target` or `class` as it's also a common convention).
> For `csv` files, it would just be slightly more complicated as we would also need to agree on an additional file format to describe the features. But once agreed, it would be relatively easy to integrate.
> 
> Not sure that `libsvm` is popular enough as a format to consider it currently.

Is there a schedule for supporting local dataset with arff format or csv format?

**Comment by seb-h2o** [comment]
No schedule. 
Support for `ARFF` file should be really simple, I can give it a try over the next few days.

If it's really urgent, we also welcome your contribution. I can guide you quickly through the code and show what needs to be implemented.

**Comment by seb-h2o** [comment]
@Tom-Deng I just found time to work on an implementation for local or remote datasets as files.
It currently only supports `.csv` and `.arff` files.
Files should be available locally, or remotely (http/https only), and also as archives (zip, tar, tgz, tbz2).

The only requirements currently:
- both training files and test files should be available (they can all be in the same archives): the app won't split the training file if the test file is missing, it will just fail.
- if dataset is pointing to a directory of an archive, then the training and test files are supposed to follow a naming convention:  for example, `xxxx_train.csv` and `xxxx_test.csv`.
- if providing multiple folds, then the naming convention is similar: `xxxx_train_0.csv`, `xxxx_test_0.csv`, `xxxx_train_1.csv`, `xxxx_test_1.csv`, ...
- the datasets still need to be defined in a benchmark definition file (no direct command line argument for now).
Examples that I used for testing, in a custom benchmark definition `~/.config/automlbenchmark/mytest.yaml` (note that this is under the default customization folder):
```
---

- name: airlines_csv
  dataset:
    train: ~/repos/h2o/h2o-3/smalldata/airlines/AirlinesTrain.csv
    test: ~/repos/h2o/h2o-3/smalldata/airlines/AirlinesTest.csv
    target: IsDepDelayed
  folds: 1

- name: chess_arff_single
  dataset:
    - ~/.openml/cache/org/openml/www/datasets/3/dataset_train_0.arff
    - ~/.openml/cache/org/openml/www/datasets/3/dataset_test_0.arff

- name: chess_arff_multi
  dataset:
    train: 
      - ~/.openml/cache/org/openml/www/datasets/3/dataset_train_0.arff
      - ~/.openml/cache/org/openml/www/datasets/3/dataset_train_1.arff
    test:
      - ~/.openml/cache/org/openml/www/datasets/3/dataset_test_0.arff
      - ~/.openml/cache/org/openml/www/datasets/3/dataset_test_1.arff
  folds: 2

- name: chess_arff_dir
  dataset: ~/.openml/cache/org/openml/www/datasets/3
  folds: 3

- name: airlines_csv_dir
  dataset:
    path: ~/repos/h2o/h2o-3/smalldata/my
    target: IsDepDelayed

- name: airlines_csv_zip
  dataset:
    path: ~/repos/h2o/h2o-3/smalldata/my/Airlines.zip
    target: IsDepDelayed

- name: airlines_csv_download_zip
  dataset:
    path: https://sebp.s3.eu-central-1.amazonaws.com/input/Airlines.zip
    target: IsDepDelayed

- name: airlines_csv_tar
  dataset:
    path: ~/repos/h2o/h2o-3/smalldata/my/Airlines_tar.tar
    target: IsDepDelayed

- name: airlines_csv_tgz
  dataset:
    path: ~/repos/h2o/h2o-3/smalldata/my/Airlines_tgz.tgz
    target: IsDepDelayed

- name: airlines_csv_bz2
  dataset:
    path: ~/repos/h2o/h2o-3/smalldata/my/Airlines_bz2.tbz
    target: IsDepDelayed

```

then I could simply run those benchmarks using :
>  python runbenchmark.py randomforest mytest

Feel free to ask any question or make any suggestion.
